### Importing Numpy and Array Type

In [ ]:
import numpy as np

In [ ]:
zero_dim_array = np.array(5)

In [ ]:
one_dim_array = np.array([1, 2, 3])

In [ ]:
n_dim_array = np.array([[1,2], [3, 4]])

In [ ]:
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



### Shape of an Array

In [ ]:
import numpy as np

In [ ]:
array_0d = np.array(5)

In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



### Reshaping an Array

In [ ]:
import numpy as np

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
reshaped_array = array.reshape(3, 2)

In [ ]:
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


### Arrays with evenly Spaced values - arange

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
x = range(1, 10)
print(x)

range(1, 10)


In [ ]:
print(list(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
x = np.arange(10.4)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
x = np.arange(0.5, 10.4, 0.8)
print(x)

[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


### Arrays with evenly spaced values -linspace

In [ ]:
import numpy as np

In [ ]:
print(np.linspace(1, 10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
print(np.linspace(1, 10, 7))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [ ]:
print(np.linspace(1, 10, 7, endpoint=False))

[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


### Initializing an Array

In [ ]:
import numpy as np

In [ ]:
ones_array = np.ones((2, 3))

In [ ]:
zeros_array = np.zeros((3, 2))

In [ ]:
empty_array = np.empty((2, 2))

In [ ]:
identity_matrix = np.eye(3)

In [ ]:
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[2.51025987e-315 0.00000000e+000]
 [4.91347521e+252 3.17095867e+180]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Converting list to array using np.array

In [ ]:
import numpy as np

In [ ]:
array_from_list = np.array([1, 2, 3])

In [ ]:
array_from_tuple = np.array((4, 5, 6))

In [ ]:
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


### From shape of an existing array

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape)

In [ ]:
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2.49784186e-315 0.00000000e+000 0.00000000e+000]
 [1.25990588e-300 1.61461882e+233 4.17723300e-287]]


### Manipulating existing array

In [ ]:
import numpy as np

In [ ]:
array = np.array([1, 2, 3])
print (array)

[1 2 3]


In [ ]:
new_array = array * 2
print (new_array)

[2 4 6]


In [ ]:
copied_array = np.copy(array)
print (copied_array)

[1 2 3]


In [ ]:
sliced_array = array[1:2]
print(sliced_array)

[2]


### With Concatenating Operation

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

In [ ]:
arr2 = np.array([[5, 6], [7, 8]])

In [ ]:
concat_axis0 = np.concatenate((arr1, arr2), axis=0)

In [ ]:
concat_axis1 = np.concatenate((arr1, arr2), axis=1)

In [ ]:
print(concat_axis0, concat_axis1, sep='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Sample Code for Indexing and Slicing

In [ ]:
import numpy as np

In [ ]:
arr1d = np.array([0, 1, 2, 3, 4, 5])

In [ ]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [ ]:
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])

In [ ]:
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]


In [ ]:
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])

Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


### Intriduction to ”ufuncs”

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3])

In [ ]:
arr2 = np.array([4, 5, 6])

In [ ]:
print("Add:", np.add(arr1, arr2))

Add: [5 7 9]


In [ ]:
print("Subtract:", np.subtract(arr1, arr2))

Subtract: [-3 -3 -3]


In [ ]:
print("Divide:", np.divide(arr1, arr2))

Divide: [0.25 0.4  0.5 ]


In [ ]:
print("Multiply:", np.multiply(arr1, arr2))

Multiply: [ 4 10 18]


In [ ]:
print("Power:", np.power(arr1, arr2))

Power: [  1  32 729]


In [ ]:
print("Exp:", np.exp(arr1))

Exp: [ 2.71828183  7.3890561  20.08553692]


### Using ”np.dot”

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
B = np.array([[7, 8], [9, 10], [11, 12]])

In [ ]:
result_dot = np.dot(A, B)

In [ ]:
print("Result with np.dot:\n", result_dot)

Result with np.dot:
 [[ 58  64]
 [139 154]]


### Using np.matmul

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
B = np.array([[7, 8], [9, 10], [11, 12]])

In [ ]:
result_at = A @ B

In [ ]:
print("Result with @ operator:\n", result_at)

Result with @ operator:
 [[ 58  64]
 [139 154]]


In [ ]:
result_matmul = np.matmul(A, B)

In [ ]:
print("Result with np.matmul:\n", result_matmul)

Result with np.matmul:
 [[ 58  64]
 [139 154]]


### Common linear algebra operation with np.linalg

In [130]:
import numpy as np

In [131]:
A = np.array([[1, 2], [3, 4]])

In [132]:
B = np.array([5, 6])

In [133]:
print("Inverse:\n", np.linalg.inv(A))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [134]:
print("Determinant:", np.linalg.det(A))

Determinant: -2.0000000000000004


In [135]:
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))

Frobenius Norm: 5.477225575051661


In [136]:
print("2-Norm (Euclidean):", np.linalg.norm(A))

2-Norm (Euclidean): 5.477225575051661


In [137]:
print("Solution x:", np.linalg.solve(A, B))

Solution x: [-4.   4.5]


### Problem - 1: Array Creation

In [139]:
import numpy as np

Initialize an empty array with size 2X2.

In [140]:
empty_array = np.empty((2, 2))
print ("Empty array: \n", empty_array)

Empty array: 
 [[1. 2.]
 [3. 4.]]


Initialize an all one array with size 4X2.

In [141]:
one_array = np.ones((4, 2))
print ("Ones array: \n", one_array)

Ones array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Return a new array of given shape and type, filled with fill value.

In [142]:
full_array = np.full((3,4), 3)
print ("Full array: \n", full_array)

Full array: 
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


Return a new array of zeros with same shape and type as a given array.

In [143]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_arr = np.zeros_like(arr)
print("Array of zeros like given array: \n", zeros_arr)

Array of zeros like given array: 
 [[0 0 0]
 [0 0 0]]


Return a new array of ones with same shape and type as a given array.

In [144]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
ones_arr = np.ones_like(arr)
print("Array of ones like given array: \n", ones_arr)

Array of ones like given array: 
 [[1 1 1]
 [1 1 1]]


For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [145]:
new_list = [1, 2, 3, 4]
list_array = np.array(new_list)
print("Numpy array from list: \n", list_array)

Numpy array from list: 
 [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [146]:
import numpy as np

Create an array with values ranging from 10 to 49.

In [147]:
array = np.arange(10,50)
print("Array ranging from 10 to 49: \n", array)

Array ranging from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3X3 matrix with values ranging from 0 to 8.

In [148]:
matrix = np.arange(9).reshape(3, 3)
print("Matrix with values ranging from 0 to 8:\n", matrix)

Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 3X3 identity matrix.

In [149]:
identity_matrix = np.eye(3)
print("A 3*3 identity matrix: \n", identity_matrix)

A 3*3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a random array of size 30 and find the mean of the array.

In [150]:
random_arr = np.random.random(30)
print("Random array : \n", random_arr)
print("Mean of the array:", random_arr.mean())

Random array : 
 [6.81377050e-01 7.21475488e-02 3.83709970e-01 6.74953949e-01
 4.60073538e-01 9.29178630e-01 9.69979167e-01 6.34363616e-02
 2.64972804e-01 9.10088067e-01 5.98792294e-01 6.53324209e-01
 7.53959236e-01 1.95574195e-01 7.17651671e-01 4.58076245e-01
 8.02666973e-01 9.67926943e-02 4.47171420e-01 7.42909914e-01
 8.33674298e-01 3.77898047e-04 2.57610178e-01 5.91104889e-01
 1.31477187e-01 2.68248923e-01 4.63736789e-01 6.87216805e-02
 9.14321941e-01 7.65988217e-01]
Mean of the array: 0.5057365979332811


Create a 10X10 array with random values and find the minimum and maximum values.

In [151]:
random_arr = np.random.random((10, 10))
print("Random array: \n", random_arr)
print("Minimum value: ", random_arr.min())
print("Maximum value: ", random_arr.max())


Random array: 
 [[0.40849113 0.44443266 0.0388345  0.9714807  0.19830952 0.55830364
  0.7120257  0.11084385 0.88560793 0.76071785]
 [0.16313349 0.19552913 0.26541778 0.42787591 0.2957735  0.59401289
  0.26602432 0.37024596 0.62602212 0.40132012]
 [0.20125612 0.99628169 0.42928544 0.05840295 0.80863079 0.28661321
  0.66849303 0.62977448 0.91901726 0.31394014]
 [0.76423624 0.21954939 0.90891596 0.45247708 0.11798592 0.21740858
  0.35273592 0.84651269 0.24005737 0.52556898]
 [0.67547079 0.34986919 0.93982544 0.16141993 0.59953148 0.3880355
  0.52636913 0.44792855 0.37625092 0.01493565]
 [0.30995332 0.38783258 0.84160658 0.24540579 0.95671328 0.80134429
  0.07623044 0.28080905 0.53511471 0.58868662]
 [0.79131546 0.18587585 0.57519191 0.57119026 0.44957057 0.58697335
  0.97738775 0.59388276 0.73724981 0.51770587]
 [0.74691237 0.17037014 0.35410417 0.26043787 0.88689645 0.89842697
  0.71104896 0.60966815 0.07424502 0.16482566]
 [0.05967175 0.75287614 0.72334367 0.84815609 0.22601342 0.161003

Create a zero array of size 10 and replace 5th element with 1.

In [152]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with %th element replaced woith 1", zero_array)

Zero array with %th element replaced woith 1 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Reverse an array arr = [1,2,0,0,4,0].

In [153]:
array = np.array([1, 2, 0, 0, 4, 0])
reverse_arr = array[::-1]
print("Reversed array is: \n", reverse_arr)

Reversed array is: 
 [0 4 0 0 2 1]


Create a 2d array with 1 on border and 0 inside.

In [154]:
array = np.ones((4, 4))
array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside is: \n", array)

2D array with 1 on border and 0 inside is: 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Create a 8X8 matrix and fill it with a checkerboard pattern.

In [155]:
checkerboard_matrix= np.zeros((8, 8))
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("Matrix with checkerboard pattern is: \n", checkerboard_matrix)

Matrix with checkerboard pattern is: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Problem - 3: Array Operations:

In [156]:
import numpy as np

In [157]:
x = np.array([[1,2],[3,5]])

In [158]:
y = np.array([[5,6],[7,8]])

In [159]:
v = np.array([9,10])

In [160]:
w = np.array([11,12])

Add the two array.

In [161]:
add = x + y
print("Adding two array : \n", add)

Adding two array : 
 [[ 6  8]
 [10 13]]


In [162]:
add = v + w
print("Adding two array : \n", add)

Adding two array : 
 [20 22]


Subtract the two array.

In [163]:
sub = x - y
print("Subtracting two array : \n", sub)

Subtracting two array : 
 [[-4 -4]
 [-4 -3]]


In [164]:
sub = v - w
print("Subtracting two array : \n", sub)

Subtracting two array : 
 [-2 -2]


Multiply the array with any integers of your choice.

In [165]:
mul = x * 2
print("Multiplied x with 2: \n", mul)

Multiplied x with 2: 
 [[ 2  4]
 [ 6 10]]


Find the square of each element of the array.

In [166]:
square = y ** 2
print("Square of y: \n", square)

Square of y: 
 [[25 36]
 [49 64]]


Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [167]:
dot_pro = np.dot(v, w)
print("Dot product between v and w: \n", dot_pro)

Dot product between v and w: 
 219


In [168]:
dot_pro = np.dot(x, v)
print("Dot product between x and v: \n", dot_pro)

Dot product between x and v: 
 [29 77]


In [169]:
dot_pro = np.dot(x, y)
print("Dot product between x and y: \n", dot_pro)

Dot product between x and y: 
 [[19 22]
 [50 58]]


Concatenate x(and)y along row and Concatenate v(and)w along column.

In [170]:
concat_xy = np.vstack((x, y))
print("Concatenate x and y along rows: \n", concat_xy)

Concatenate x and y along rows: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [172]:
concat_vw = np.column_stack((v, w))
print("Concatenate v and w along column: \n", concat_vw)

Concatenate v and w along column: 
 [[ 9 11]
 [10 12]]


Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

The error is occured because x has shape of (2,2) i.e. 2D and v has shape of (2,) i.e 1D and NumPy requires the same number of dimensions.

In [173]:
concat_xv = np.concatenate((x, v))
print("Concatenate x and v: \n", concat_xv)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### Problem - 4: Matrix Operations:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = (B)T(A)T

In [174]:
import numpy as np

In [175]:
A = np.array([[3,4],[7,8]])

In [176]:
B = np.array([[5,3],[2,1]])

In [177]:
A_inverse = np.linalg.inv(A)
print("The inverse of A is: \n", A_inverse)

The inverse of A is: 
 [[-2.    1.  ]
 [ 1.75 -0.75]]


In [178]:
identity = A @ A_inverse
print("A * A_inverse is: \n", identity)

A * A_inverse is: 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [179]:
AB = np.dot(A, B)
print("The product of AB is:\n", AB)

The product of AB is:
 [[23 13]
 [51 29]]


In [180]:
BA = np.dot(B, A)
print("The product of BA is:\n", BA)

The product of BA is:
 [[36 44]
 [13 16]]


In [181]:
print("Is AB equals to BA?? ", np.array_equal(AB, BA))

Is AB equals to BA??  False


In [182]:
LHS = (A @ B).T

In [183]:
RHS = B.T @ A.T

In [186]:
print("(AB)^T:\n", LHS)

(AB)^T:
 [[23 51]
 [13 29]]


In [187]:
print("B^T A^T:\n", RHS)

B^T A^T:
 [[23 51]
 [13 29]]


In [188]:
print("Is (AB)^T and B^T A^T equal?", np.array_equal(LHS, RHS))

Is (AB)^T and B^T A^T equal? True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [189]:
import numpy as np

In [190]:
A = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])

In [191]:
B = np.array([-1, -3, 9])

In [192]:
A_inverse = np.linalg.inv(A)

In [193]:
X = A_inverse @ B

In [194]:
print("The solution of X is: \n", X)

The solution of X is: 
 [ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.

In [195]:
X1 = np.linalg.solve(A, B)
print("Solution using np.linalg.inv function is:\n", X1)

Solution using np.linalg.inv function is:
 [ 2.  1. -2.]


### Experiment: How Fast is Numpy?

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [196]:
import numpy as np

In [197]:
import time

In [198]:
list1 = list(range(1_000_000))

In [199]:
list2 = list(range(1_000_000))

In [200]:
start_time = time.time()
result = [list1[i] + list2[i] for i in range(1_000_000)]
end_time = time.time()

In [201]:
print("Python List Addition Time Taken i:", end_time - start_time)

Python List Addition Time Taken i: 0.06260132789611816


In [202]:
array1 = np.arange(1_000_000)

In [203]:
array2 = np.arange(1_000_000)

In [204]:
start_time = time.time()
numpy_add = array1 + array2
end_time = time.time()

In [205]:
print("NumPy Array Addition Time Taken is:", end_time - start_time)

NumPy Array Addition Time Taken is: 0.0023708343505859375


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [206]:
list1 = list(range(1_000_000))

In [207]:
list2 = list(range(1_000_000))

In [208]:
start_time = time.time()
mul_lists = [list1[i] * list2[i] for i in range(1_000_000)]
end_time = time.time()

In [209]:
print("Python List Multiplication Time Taken is:", end_time - start_time)

Python List Multiplication Time Taken is: 0.06506633758544922


In [210]:
array1 = np.arange(1_000_000)

In [211]:
array2 = np.arange(1_000_000)

In [212]:
start_time = time.time()
numpy_mul = array1 * array2
end_time = time.time()

In [213]:
print("NumPy Array Multiplication Time Taken is:", end_time - start_time)

NumPy Array Multiplication Time Taken is: 0.002620697021484375


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [214]:
start_time = time.time()
dot_pro = sum(list1[i] * list2[i] for i in range(1_000_000))
end_time = time.time()

In [215]:
print("Python List Dot Product Time Taken is:", end_time - start_time)

Python List Dot Product Time Taken is: 0.06446003913879395


In [216]:
start_time = time.time()
numpy_dot_pro = np.dot(arr1, arr2)
end_time = time.time()

In [217]:
print("NumPy Array Dot Product Time Taken is:", end_time - start_time)

NumPy Array Dot Product Time Taken is: 0.00010395050048828125


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [218]:
N = 200

In [219]:
A = [[i + j for j in range(N)] for i in range(N)]

In [220]:
B = [[i * j for j in range(N)] for i in range(N)]

In [221]:
start_time = time.time()
C = [[sum(A[i][k] * B[k][j] for k in range(N)) for j in range(N)] for i in range(N)]
end_time = time.time()

In [222]:
print("Python List Matrix Multiplication of size 200 * 200 Time Taken is:", end_time - start_time)

Python List Matrix Multiplication of size 200 * 200 Time Taken is: 0.5543136596679688


In [223]:
N = 1000

In [224]:
A = [[i + j for j in range(N)] for i in range(N)]

In [225]:
B = [[i * j for j in range(N)] for i in range(N)]

In [226]:
A_np = np.array(A)

In [227]:
B_np = np.array(B)

In [228]:
start_time = time.time()
C_np = np.dot(A_np, B_np)
end_time = time.time()

In [229]:
print("NumPy Array Matrix Multiplication of size 1000*1000 Time Taken is:", end_time - start_time)

NumPy Array Matrix Multiplication of size 1000*1000 Time Taken is: 0.8450043201446533
